# Generated by Django 2.2.12 on 2022-12-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='item_active',
            field=models.IntegerField(default=1),
        ),
    ]
